<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="HMDNYC-41RVJGH5" name="com.toy.dataproviders.DataProvidersEsp" tests="1" failures="0" timestamp="11 Nov 2020 19:38:18 GMT" time="0.000" errors="1">
  <testcase name="testss" time="0.000" classname="com.toy.dataproviders.DataProvidersEsp">
    <error type="org.testng.TestNGException" message="
Method public void com.toy.dataproviders.DataProvidersEsp.testss(java.lang.String,java.lang.String,java.lang.String) requires a @DataProvider named : Disclaimer in class com.toy.dataproviders.DataProvidersEsp">
      <![CDATA[org.testng.TestNGException: 
Method public void com.toy.dataproviders.DataProvidersEsp.testss(java.lang.String,java.lang.String,java.lang.String) requires a @DataProvider named : Disclaimer in class com.toy.dataproviders.DataProvidersEsp
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:263)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:419)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1270)
	at org.testng.internal.Invoker.createParameters(Invoker.java:985)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1075)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testss -->
</testsuite> <!-- com.toy.dataproviders.DataProvidersEsp -->
